#include <openssl/ssl.h>
typedef struct Websocket{
	char* Id;
	char* userid;
	char* sessionid;
	char* connected_on;
	char* name;
	char*  socketId;
	int exists;
}websockets;
struct Websocket* get_websocket_session_by_name(char* sessionName,size_t *total_sessions);
int is_active_websocket_client(int fd);
struct Websocket get_websocket_session(char* sessionId);
char* get_websocket_sessions_by_userId(char* userid);
int websocket_session_exists(char* sessionId);
char* convert_websockets_to_json(struct Websocket* websocket, int count);
char* convert_websocket_to_json(struct Websocket websocket);
struct Websocket create_websocket_session(char* name, char* userid);
char* generate_websocket_accptKey(char* websocket_sec_key);
// int is_websocket_buffer(unsigned char* buf);
int decode_websocket_buffer(unsigned char* buf, char message[] );
void insert_websocket_session(struct Websocket websocket);
struct Websocket get_websocket_by_Id(char* Id);
char* create_websocket_buffer();
void send_websocket_buffer(SSL* cSSL, char* buf);
void close_websocket_connection();
// int is_websocket_buffer(unsigned char* buf);
void update_sessionName_by_sessionId(char* sessionId, char* name);
char*  get_websockets();
void delete_websocket_by_fd(int fd);
void delete_websocket_by_sessionid(char* sessionid);
